name: "Billy"
greeting: "Howdy"
command('hello -name=<name> -email=<email> there'): |
  echo "Hello <name>";
#command('state (enable|disable)'): |
#  echo "Hello ={ input.command(1) }";
#command('hello <name>'):
#  env:
#    NAME: = input.argument('name')
#  exec: |
#    #!bash
#    echo -n "hello ${NAME}"
confd('/'):
  - { src: test1.txt.tmpl, dst: test1.txt }
  - { src: test2.txt.tmpl, dst: test2.txt }